// Shared colors for form components
export const colors = {
  primary: '#1E8AD9',
  primaryDark: '#0d6bb6',
  success: '#64D4C6',
  danger: '#dc3545',
  warning: '#ffc107',
  neutral: '#f8f9fa',
  border: '#dee2e6',
  borderLight: '#f0f1f3',
  text: '#212529',
  textMuted: '#6c757d',
  disabled: '#e9ecef',
};

// Reusable style objects for form sections
export const formStyles = {
  section: {
    marginBottom: '2.5rem',
  },
  section_title: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: colors.text,
    marginBottom: '1.5rem',
  },
  label: {
    display: 'block' as const,
    marginBottom: '0.5rem',
    fontWeight: '500',
    color: colors.text,
    fontSize: '0.95rem',
  },
  required: {
    color: colors.danger,
  },
  input: {
    width: '100%',
    padding: '0.65rem 0.75rem',
    fontSize: '0.95rem',
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    fontFamily: 'inherit',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)',
  },
  textarea: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '0.95rem',
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    fontFamily: 'inherit',
    resize: 'vertical' as const,
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.08)',
    minHeight: '6rem',
    lineHeight: '1.5',
  },
  moduleCard: {
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
    background: '#fff',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
    transition: 'all 0.2s ease',
  },
  module_header: {
    display: 'flex' as const,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1.5rem',
  },
  module_title: {
    fontSize: '1.2rem',
    fontWeight: '600',
    color: colors.text,
    margin: 0,
  },
  button_primary: {
    padding: '0.75rem 1.5rem',
    background: colors.primary,
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.95rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  button_secondary: {
    padding: '0.5rem 1.5rem',
    background: colors.neutral,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.95rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
  button_success: {
    width: '100%',
    padding: '0.85rem 1.5rem',
    background: colors.success,
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: '500',
    fontSize: '0.95rem',
    transition: 'all 0.2s ease',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
  },
  button_success_disabled: {
    width: '100%',
    padding: '0.85rem 1.5rem',
    background: colors.disabled,
    color: colors.textMuted,
    border: 'none',
    borderRadius: '6px',
    cursor: 'not-allowed',
    fontWeight: '500',
    fontSize: '0.95rem',
    opacity: 0.6,
  },
  button_danger: {
    padding: '0.35rem 0.75rem',
    background: colors.danger,
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.875rem',
    fontWeight: '500',
    transition: 'all 0.2s ease',
    boxShadow: '0 1px 3px rgba(0,0,0,0.12)',
  },
  fieldGroup: {
    display: 'flex' as const,
    flexDirection: 'column' as const,
    gap: '1.5rem',
  },
  fieldRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  hr: {
    border: 'none',
    borderTop: `1px solid ${colors.border}`,
    margin: '2rem 0',
  },
  contractSection: {
    padding: '0.5rem',
    marginBottom: '1rem',
  },
  contractTitle: {
    fontSize: '1.6rem',
    fontWeight: '700',
    color: colors.primary,
    marginBottom: '1.5rem',
    letterSpacing: '0.75px',
  },
  contractPreview: {
    fontSize: '0.95rem',
    lineHeight: '1.8',
    color: colors.text,
    fontStyle: 'italic' as const,
  },
  contractValue: {
    borderBottom: `2px solid ${colors.primary}`,
    color: colors.text,
    fontWeight: '600',
    fontStyle: 'normal' as const,
    paddingBottom: '2px',
  },
};
